spring:
  application:
    name: data-processing-pipeline
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/data_processing_pipeline}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

logging:
  level:
    liquibase: INFO
    com.laris.dataprocessingpipeline: DEBUG

jwt:
  secret: ${JWT_SECRET:YOUR_SECRET_HERE}
  expiration: 86400000  #24 hours

city-aggregator:
  cities-file-path: ${CITIES_FILE_PATH:src/main/resources/cities.txt}
  apis:
    openweathermap:
      base-url: https://api.openweathermap.org/data/2.5
      api-key: ${OPENWEATHER_API_KEY:YOUR_API_KEY_HERE}
    youtube:
      base-url: https://www.googleapis.com/youtube/v3
      api-key: ${YOUTUBE_API_KEY:YOUR_API_KEY_HERE}
    nominatim:
      base-url: https://nominatim.openstreetmap.org
      user-agent: DataProcessingPipeline/1.0
    wikipedia:
      base-url: https://en.wikipedia.org/api/rest_v1
